Zverik/every_door

lib/helpers/changeset_tags.dart
lib/screens/settings/log.dart

I think the platforms should be capitalized.

Capitalization of 'Android' and 'iOS' in `created_by` changeset tags

---

README.md

Seems that my markdown preview tool do not use the same layout as GitHub...
Here is a simple PR to align the 3 screenshots of the same row.

Set screenshots on a single row

---

lib/l10n/app_en.arb
lib/screens/settings.dart
lib/screens/settings/about.dart
pubspec.lock
pubspec.yaml

Resolves https://github.com/Zverik/every_door/issues/238
This adds some meta info to the settings page, in a new "About" section, as per the screenshot. Also moves the system log to it's own dedicated button.
I did try a dedicated "About" page, but it seemed a bit sparse, so a section on the main settings page seemed better.
As always, thanks!

Add "About" section to settings page

---

lib/helpers/good_tags.dart

Hide [amenity=lounger](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dlounger) which is similar to amenity=bench
There are 3227 uses in [Taginfo](https://taginfo.openstreetmap.org/tags/amenity=lounger)
| Before | After |
| - | - |
| ![image](https://user-images.githubusercontent.com/2798728/184181935-697b1b26-8d65-4d1b-91dd-a393bb84ef0d.png) | ![image](https://user-images.githubusercontent.com/2798728/184182363-2dcd05f5-ac41-41a2-a25b-5c82a714ee78.png) |

Hide amenity=lounger

---

lib/screens/settings/language.dart

Dart code changes for settings display:
`zh-hans`: `汉语（简体）`
`zh-hant`: `漢語（繁體）`
@Supaplextw are these the preferred display names for each locale?

Add UI display for zh-hant and zh-hans locales [#377]

---

lib/screens/settings/language.dart

I appreciate you merging the translation for `pa_PK` - this is just an adjustment to the name to be in the Perso-Arabic script used in Pakistan. I have it just saying "Punjabi" `پنجابی` and `pa` says `ਪੰਜਾਬੀ` since I think this is simpler. (The user can tell which one to choose based on the writing system difference).

pa_PK language name in script

---

lib/helpers/normalizer.dart

When searching for any feature in the preset that contains a voiced or semi-voiced mark in the name, if the input is in Japanese and there is a voiced mark or semi-voiced mark, the feature will not be displayed, but if the input is without the voiced mark, the feature will be displayed.
This seems to be due to the voiced and semi-voiced marks being removed in the database but not in the search query.
Therefore, although it is simplified, I added replacement targets to the normalizer and automatically removes the voiced and semi-voiced marks in the Japanese for the search query.
( Fix #517 )

Fix search not working for features that contain voiced or semi-voiced marks in Japanese

---

lib/helpers/tag_emoji.dart

otherwise build fails with:
```
lib/helpers/tag_emoji.dart:32:3: Context: The key '"amenity=toilets"' conflicts with another existing key in the map.
```

remove duplicate amenity=toilets value

---

.github/workflows/build-apk.yml

Allows users to build Android `.apk` via GitHub Actions, without having flutter/Android development environment on their computer.

GitHub actions for manual build of .apk

---

lib/screens/settings/account.dart

Before, if the OSM profile image is very tall, it was very close to the username.
This adds a small gap between the username and the picture.
Before/after image:

fix: add space between the profile image & username

---

lib/screens/settings.dart

On a `SettingsTile`, even if the `description` is an empty string, space is still left for description text.
This means that when you aren't logged in, the "OSM Account" text is not vertically centred.
Before/after:

minor fix: OSM Account settings tile offset when logged out

---

lib/helpers/good_tags.dart

`mountain_rescue`, `ses_station`, `water_rescue`, `air_rescue_service` are all POIs, i.e. permanent stations, that should show up in POI mode, not micromapping mode.
I have just made this edit in the browser, so it is untested.

Show other `emergency` features as POIs

---

android/app/build.gradle

Attributes about sdk version have changed in Gradle 7.0 -> more information here https://stackoverflow.com/questions/67250362/what-is-difference-between-compilesdk-and-compilesdkversion-in-android-studio-gr/67251145#67251145

Use new attributes in gradle script

---

.github/workflows/fdroid.yml

the original GitHub workflow did not save the artifacts, so anything built was discarded after completion of the job.

create .apk for fdroid build too

---

lib/helpers/tags/common_keys.dart

Added this key to the list of common keys:
https://wiki.openstreetmap.org/wiki/Key:ref:RS:kucni_broj
Values for this key are stored in buildings, addresses, entrances, POIs, etc. in Serbia.
I didn't test the app with this change.

Added ref:RS:kucni_broj to common_keys.dart

---

lib/helpers/tags/element_kind_std.dart

i.e. both should be in `Amenity mode`; because they are basically the same (just different type of "fuel")
Fixes https://github.com/Zverik/every_door/issues/901
(I have not tested it yet, though)

amenity=charging_station should be treated like amenity=fuel

---

tools/language_codes.csv

Added Latin version of Serbian language to language_codes.csv.
https://wiki.openstreetmap.org/wiki/Item:Q1575
Do I need to add it elsewhere?

Add sr-Latn to language_codes.csv

---

lib/l10n/app_en.arb

Fixes #868 
Description:
- Updated the FAQ to reflect the new file structure.
- Replaced the outdated good_tags.dart link with the correct element_kind_std.dart link.
- Adjusted FAQ content for clarity and consistency with the updated tagging system.

Update FAQ Link to Correct Tags File

---

lib/screens/settings/log.dart

Fix #842 
Added a dedicated copy button in the app bar of System Log screen to copy all logs.
<p align="center">
</p>

Added copy all logs functionality

---

lib/fields/text.dart
lib/models/field.dart

A clear (X) button was added to the fixme field in the editor. It appears only when the field has text and clears both the controller and element data on tap. Uses existing tagsDelete translation for the tooltip. Fix #843.
Screenshot:
<p>
</p>

Added clear button to fixme input field

---

lib/screens/settings/install_plugin.dart

Minor rewording of error message to improve clarity.
From: 'The plugin has been already installed and of the latest version.'
→ To: 'The latest version of the plugin has already been installed.'

Reword error message
